### ISSUE TITLE
Needed support of timers

### ISSUE THREAD

**Issue by ghost** [raydac/ravikoodi-server#1]
Hello._(Sorry for my English)_ This program is what I need and what, but I really need one new function - start playing file on timer and stop it on timer too. For example, I want start playing file at 9:00, then stop at 10:15, and again(for example start at 11:00 and stop at 12:00). **I REALLY NEED THIS!!!**

**Comment by NikShn2004** [comment]
For example in Kodi I can add timers, which will turn on TV show on at preset time and turn off at preset time.

![unnamed](https://user-images.githubusercontent.com/40064591/87232097-1c5c3500-c3c5-11ea-8df5-88748ab14b99.png)

**Comment by NikShn2004** [comment]
This is example, what I want.

![123](https://user-images.githubusercontent.com/40064591/87232290-5a0d8d80-c3c6-11ea-8f2a-edde1498557b.png)

**Comment by raydac** [comment]
I will think how to implement the feature

**Comment by raydac** [comment]
@NikShn2004 you can try [1.1.3-SNAPSHOT](https://github.com/raydac/ravikoodi-server/releases/tag/1.1.3-S), timers are accessible through __Tools->Timers__
![image](https://user-images.githubusercontent.com/3008810/87873990-c98b0a80-c9ce-11ea-900b-a0bdd80c4149.png)

**Comment by NikShn2004** [comment]
Тhank you very much, I will test it and then write to you.

**Comment by raydac** [comment]
@NikShn2004 did you have time to try?

**Comment by NikShn2004** [comment]
I'm sorry, but I haven't had time yet. I'll definitely try it tomorrow.

**Comment by NikShn2004** [comment]
I am working on Windows. I cant set up time for timer. This is video: 
[https://yadi.sk/i/YacZ8Uf_cldl3A](https://yadi.sk/i/YacZ8Uf_cldl3A)

**Comment by NikShn2004** [comment]
And another problem.
![image](https://user-images.githubusercontent.com/40064591/88518707-97def880-cff9-11ea-93bb-56ba5c00370f.png)
This panel doesnt working with new versions of kodi - 18.xx,    but it works with 17.xx versions.

**Comment by raydac** [comment]
да, можно по русски
с вводом времени надо enter нажимать, но я пофикшу чтобы запоминаось и при потере фокуса, с коди 18 гляну что за дела, наверное в API поменяли чтонить

**Comment by NikShn2004** [comment]
Таймер запускает файл, но не выключает, скорей всего из-за выше перечисленной проблемы. 
P.S. Если можно сделайте пожалуйста, чтобы если таймер еще активен, но видео закончилось, то оно запускалось еще раз, и так пока таймер не закончится.

**Comment by raydac** [comment]
пофиксил несовместимость с 18.xx

**Comment by raydac** [comment]
добавил повторение контента если специальный флаг repeat у таймера выставлен, можно в снапшот версии попробовать

**Comment by NikShn2004** [comment]
Огромное спасибо, на днях протестирую.

**Comment by NikShn** [comment]
Перестало отключаться по таймеру.

**Comment by NikShn** [comment]
Но repeat работает

**Comment by raydac** [comment]
т.е. запускается видео, повторяется, но когда должно остановиться то не останавливается? или останавливается на следующем повторении?

**Comment by NikShn** [comment]
Оно останавливается уже когда само по себе закончится(ну и таймер больше не действует). Даже в стандартном режиме без галочки "повтор", видео и изображения не выключаются.

**Comment by NikShn** [comment]
То-есть просто выключение по таймеру не работает в любых режимах.(но через панель выключить можно)(вручную)

**Comment by raydac** [comment]
сделал фикс, можно попробовать снапшот

**Comment by NikShn** [comment]
Быстренько протестировал, все работает, еще раз вам огромное спасибо! Эта кнопка для доната актуальная?
![Screenshot_7](https://user-images.githubusercontent.com/40064591/89128041-5a97d080-d4fb-11ea-9028-e0caebd9429c.png)

**Comment by raydac** [comment]
гуд, тогда релиз сделаю сегодня-завтра
кнопка вроде актуальная если яндекс.деньги никаких нововведений не сделал, пайпал тоже актуален

**Comment by NikShn** [comment]
Задонатил.

**Comment by raydac** [comment]
да, пришло, спасибо огромное!
